name: build

on:
  pull_request:
  push:
    paths-ignore:
    - "README.md"
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [windows-2019,ubuntu-22.04,macos-latest]
        lazarus-versions: [dist]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    #    include-packages: "Synapse 40.1"
        with-cache: true
    - name: Build the Main Application
      if: ${{ matrix.operating-system != 'macos-latest' }}
      run: lazbuild -B "src/ProteusModelBuilder.lpi"
    - name: Build the Main Application (macOS)
      if: ${{ matrix.operating-system == 'macos-latest' }}
      run: lazbuild -B --ws=cocoa "src/ProteusModelBuilder.lpi"
 #   - name: Build the Unit Tests Application
 #     run: lazbuild -B "tests/testconsoleapplication.lpi"
  #  - name: Run the Unit Tests Application
  #    run: bin/testconsoleapplication "--all" "--format=plain"
